<a href="https://colab.research.google.com/github/monicasjsu/deep_learning/blob/master/1_tensors_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor fundamentals**

In [0]:
a = [1.0, 2.0, 1.0]

Accessing the first element of the list by using the corresponding 0-based index

In [3]:
a[0]

1.0

In [4]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

constructing first PyTorch tensor to see what it looks like

In [5]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [0]:
points = torch.zeros(6)
points[0] = 1.0
points[1] = 4.0
points[2] = 2.0
points[3] = 1.0
points[4] = 3.0
points[5] = 5.0

We can also pass a Python list to the constructor to the same effect

In [10]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
points

tensor([1., 4., 2., 1., 3., 5.])

We can get the coordinates of the first points using float

In [11]:
float(points[0]), float(points[1])

(1.0, 4.0)

We can use a 2D tensor for the same process mentioned above


In [12]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

Checking the shape of the tensor

In [13]:
points.shape

torch.Size([3, 2])

Initializing the tensor with zeros to mention the size of the tuple

In [14]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

 Accessing an individual element in the tensor by using two indices which will returns the y coordinate of the 0th point in your data set

In [16]:
points[0, 1]

tensor(4.)

Trying to acces the first element in the tensor as we did before to get the 2D coordinates of the first point

In [17]:
points[0]

tensor([1., 4.])

**Tensors and storages**

Indexing into storage with 2D points. Accessing the storage for a given tensor

In [18]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

Indexing into the storage manually

In [19]:
points_storage = points.storage()
points_storage[0]

1.0

In [20]:
points.storage()[1]

4.0

Changing the value of a storage which changes the content of its referring tensor

In [21]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])

**Size, storage offset, and strides**

 Getting the second point in the tensor by providing the corresponding index

In [22]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.storage_offset()

2

In [23]:
second_point.size()

torch.Size([2])

In [24]:
second_point.shape

torch.Size([2])

Using stride to skip the number of elements in the storage by increasing the index by 1 in each dimension

In [25]:
points.stride()

(2, 1)

In [26]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point.size()

torch.Size([2])

In [27]:
torch.Size([2])

torch.Size([2])

In [28]:
second_point.storage_offset()

2

In [29]:
second_point.stride()

(1,)

Changing the subtensor has a side effect on the original tensor too

In [30]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])

Cloning the subtensor into a new tensor

In [31]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [32]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

Using transpose to change the columns into rows and vice-versa

In [33]:
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

 Verifying that the two tensors share storage

In [34]:
id(points.storage()) == id(points_t.storage())

True

In [35]:
points.stride()

(2, 1)

In [36]:
points_t.stride()

(1, 2)

Transposing a multidimensional array by specifying the two dimensions along which transposing should occur

In [37]:
some_tensor = torch.ones(3, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2)
some_tensor.shape

torch.Size([3, 4, 5])

In [38]:
some_tensor_t.shape

torch.Size([5, 4, 3])

In [39]:
some_tensor.stride()

(20, 5, 1)

In [40]:
some_tensor_t.stride()

(1, 5, 20)

Checking if the points is contiguous but its transpose is not

In [41]:
points.is_contiguous()

True

In [42]:
points_t.is_contiguous()

False

In [43]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
points_t

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [44]:
points_t.storage()

 1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]

In [45]:
points_t.stride()

(1, 2)

In [46]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 2., 3.],
        [4., 1., 5.]])

In [47]:
points_t_cont.stride()

(3, 1)

In [48]:
points_t_cont.storage()

 1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]

**Numeric types**

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [50]:
short_points.dtype

torch.int16

In [0]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

Casting the output of a tensor-creation function to the right type by using the corresponding casting method

In [0]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

Casting a tensor of one type as a tensor of another type by using the
type method

In [0]:
points = torch.randn(10, 2)
short_points = points.type(torch.short)

**Indexing Tensors**

In [54]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

In [55]:
points[1:]
points[1:, :]
points[1:, 0] 

tensor([-0.8511, -0.7367,  0.2424, -0.3277, -0.5710,  0.3874,  0.9535, -0.4379,
         0.0188])

**NumPy interoperability**

Getting a NumPy array out of the points tensor

In [56]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

Obtaining a PyTorch tensor from a NumPy array
which uses the same buffer-sharing strategy.

In [0]:
points = torch.from_numpy(points_np)

**Serializing tensors**

Saving our points tensor to a ourpoints.t file

In [0]:
torch.save(points, 'drive/My Drive/data/p1ch3/ourpoints.t')

In [0]:
import h5py

f = h5py.File('drive/My Drive/data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

**Moving tensors to the GPU**

In [0]:
points_gpu = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 4.0]],
device='cuda')

In [0]:
points_gpu = points.to(device='cuda')

Multiplying all elements
by a constant, is carried out on the GPU

In [0]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda') 

Adding a constant to the result

In [0]:
points_gpu = points_gpu + 4

Moving the tensor back to the
CPU, we need to provide a cpu argument to the to method

In [0]:
points_cpu = points_gpu.to(device='cpu')

**The Tensor API**

In [0]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

In [0]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

In [0]:
a = torch.ones(3, 2)

In [76]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])