<a href="https://colab.research.google.com/github/monicasjsu/deep_learning/blob/master/keras_multiclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, f1_score, recall_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import  train_test_split
from keras.models import Model, load_model
from keras.layers import Input, Dense
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras import regularizers
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense,Dropout, Flatten
from keras.optimizers import Adam,sgd
from sklearn.metrics import mean_absolute_error
from keras import layers, metrics
import keras

Using TensorFlow backend.


In [0]:
df = pd.read_csv("/content/drive/My Drive/Datasets/dl_2/winequality.csv")

In [3]:
df

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
df.quality.unique()

array([5, 6, 7, 4, 8, 3])

As we can see; our target label is an "integer type" which has to be converted into categorical value in order to use in keras.

In [0]:
df['quality'] = df['quality'].apply(str)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   object 
dtypes: float64(11), object(1)
memory usage: 150.0+ KB


In [8]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [9]:
output = df["quality"]
input = df.drop(['quality'],axis=1)
output

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: object

As we are working with multi class classification using keras, we use label encosing to encode all the classes present in the dataset. 

In [10]:
encoding = LabelEncoder()
encoding.fit(output)
encode_quality = encoding.transform(output)
df_ylabel = np_utils.to_categorical(encode_quality)
print(df_ylabel)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [0]:
def model():
	model = Sequential()
	model.add(Dense(8, input_dim=4, activation='relu'))
	model.add(Dense(3, activation='softmax'))
	model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
	return model

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
estimator = KerasClassifier(build_fn=model, epochs=100, batch_size=5, verbose=0)

In [0]:
from sklearn.model_selection import KFold
kfold = KFold(n_splits=6, shuffle=True)

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(input,df_ylabel,test_size=0.3,random_state=0)

In [0]:
def runAlgo(X_train,X_test,y_train,y_test):
    model = Sequential()
    model.add(Dense(10, activation="relu",input_shape=(11,)))
    model.add(Dropout(0.001))
    model.add(Dense(6,activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=300)
    a = model.evaluate(X_test, y_test)
    return a

In [16]:
runAlgo(X_train,X_test,y_train,y_test)

Epoch 1/300
1119/1119 [==============================] - 0s 106us/step - loss: 1.8371 - accuracy: 0.3825
Epoch 2/300
1119/1119 [==============================] - 0s 32us/step - loss: 1.5300 - accuracy: 0.4638
Epoch 3/300
1119/1119 [==============================] - 0s 32us/step - loss: 1.4440 - accuracy: 0.4763
Epoch 4/300
1119/1119 [==============================] - 0s 32us/step - loss: 1.3756 - accuracy: 0.4861
Epoch 5/300
1119/1119 [==============================] - 0s 32us/step - loss: 1.3221 - accuracy: 0.4897
Epoch 6/300
1119/1119 [==============================] - 0s 33us/step - loss: 1.2926 - accuracy: 0.4888
Epoch 7/300
1119/1119 [==============================] - 0s 36us/step - loss: 1.2707 - accuracy: 0.4870
Epoch 8/300
1119/1119 [==============================] - 0s 35us/step - loss: 1.2455 - accuracy: 0.4888
Epoch 9/300
1119/1119 [==============================] - 0s 33us/step - loss: 1.2329 - accuracy: 0.4960
Epoch 10/300
1119/1119 [==============================] - 0s 38

[0.9420280814170837, 0.6312500238418579]