In [1]:
import numpy as np

# computation of arrays:Broadcasting
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
a + b

array([3, 5, 7])

In [2]:
a + 5

matrix = np.ones((2, 2))
print(matrix)

[[1. 1.]
 [1. 1.]]


In [3]:
c = np.arange(3)
d = np.arange(3)[:, np.newaxis]
print(c)
print(d)



[0 1 2]
[[0]
 [1]
 [2]]


In [4]:
print(c + d)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [5]:
X = np.random.random((1, 2))
print(X)

print(X.mean(0))

[[0.26560332 0.21550551]]
[0.26560332 0.21550551]


In [6]:
print(X - X.mean(0))

[[0. 0.]]


In [7]:
A = np.array([[10, 20, 30], [11, 21, 31], [12, 22, 32]])
print(A)

[[10 20 30]
 [11 21 31]
 [12 22 32]]


In [8]:
B = 1
print(B)

1


In [9]:
c = A + B
print(c)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [10]:
M = np.ones((3, 3))
print(M)

k = ([5, 6, 7])

print(M + k)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[6. 7. 8.]
 [6. 7. 8.]
 [6. 7. 8.]]


In [11]:
# Numpy Array Attributes

x1 = np.random.randint(10, size=(2, 2))
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)
print("dtype:", x1.dtype)
print("itemsize:", x1.itemsize, "bytes")

print(x1)

print(x1[0])

x1 ndim:  2
x1 shape: (2, 2)
x1 size:  4
dtype: int64
itemsize: 8 bytes
[[1 6]
 [2 7]]
[1 6]


In [12]:
x2 = np.random.randint(10, size=(4,4))
print(x2)

print(x2[3,2])

[[3 5 3 9]
 [0 8 4 5]
 [5 5 6 8]
 [9 0 1 1]]
1


In [13]:
x = np.arange(10)
print(x)

print(x[:5])

print(x[2:7])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[2 3 4 5 6]


In [14]:
a = np.arange(16).reshape(4, 4)
print(a)
np.diag(a)
np.einsum(a, [0,0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

In [15]:
y = 20 * np.ones(100)

np.einsum('i->', y)

2000.0

In [16]:

A = np.array([[1, 1],
           [2, 2]])

B = np.array([[0, 1],
           [1, 1]])

# matrix multiplication using normal way
k = (A[:, np.newaxis] * B).sum(axis=1)
print(k)

# matrix multiplication using einsum
x = np.einsum('ij,jk', A, B)
print(x)


[[1 2]
 [2 4]]
[[1 2]
 [2 4]]


In [17]:
# Tensor Contraction
x = np.arange(36.).reshape(3,4,3)
y = np.arange(24.).reshape(4,3,2)
np.einsum('ijk,jil->kl', x, y)

array([[2640., 2838.],
       [2772., 2982.],
       [2904., 3126.]])

In [18]:
# Transpose of a matrix
np.transpose(a)


array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])